# This is a basic workflow to help you get started with Actions

name: greetings

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

